model:
  users:
    name:
      maximum: 50
    email:
      maximum: 255
    address:
      maximum: 400
    phone:
      maximum: 11
    password:
      minimum: 6
  suggests:
    title:
      maximum: 255
  categories:
    name:
      maximum: 50
session:
  remember_me: 1
timeout:
  reset_sent: 2
rows: 15
accept_img: "image/jpeg,image/gif,image/png"
size_img: 400
image_times: 4
image:
  height: 100%
  width: 100%
new_foods_limit: 4
rating_stars: 5
format_time: "%H:%M:%S %d/%m/%Y"
most_ordered_foods: 5
gmap_options: "&size=300x300&zoom=17"
